<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8"></meta>
	<title>DataTables</title>
	<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css">

</head>
<body>
	<div class="container">
		<div class="row">
			<table class="table" id="myTable">
				<thead>
					<th>Name</th>
					<th>Position</th>
					<th>Place</th>
					<th>Phone</th>
				</thead>
				<tfoot>
					<th>Name</th>
					<th>Postion</th>
					<th>Place</th>
					<th>Phone</th>					
				</tfoot>
				<tbody>
				<tr>
					<td>ABC</td>
					<td>1</td>
					<td>Dhaka</td>
					<td>12345</td>
				</tr>	
				<tr>
					<td>ABC</td>
					<td>1</td>
					<td>Dhaka</td>
					<td>12345</td>
				</tr>
				<tr>
					<td>ABC</td>
					<td>1</td>
					<td>Dhaka</td>
					<td>12345</td>
				</tr>

				<tr>
					<td>ABC</td>
					<td>1</td>
					<td>Dhaka</td>
					<td>12345</td>
				</tr>
				<tr>
					<td>ABC</td>
					<td>1</td>
					<td>Dhaka</td>
					<td>12345</td>
				</tr>
				<tr>
					<td>ABC</td>
					<td>1</td>
					<td>Dhaka</td>
					<td>12345</td>
				</tr>
				<tr>
					<td>ABC</td>
					<td>1</td>
					<td>Dhaka</td>
					<td>12345</td>
				</tr>
				<tr>
					<td>ABC</td>
					<td>1</td>
					<td>Dhaka</td>
					<td>12345</td>
				</tr>
				<tr>
					<td>ABC</td>
					<td>1</td>
					<td>Dhaka</td>
					<td>12345</td>
				</tr>
				<tr>
					<td>ABC</td>
					<td>1</td>
					<td>Dhaka</td>
					<td>12345</td>
				</tr>
				<tr>
					<td>ABC</td>
					<td>1</td>
					<td>Dhaka</td>
					<td>12345</td>
				</tr>
				<tr>
					<td>ABC</td>
					<td>1</td>
					<td>Dhaka</td>
					<td>12345</td>
				</tr>
				<tr>
					<td>ABC</td>
					<td>1</td>
					<td>Dhaka</td>
					<td>12345</td>
				</tr>
				<tr>
					<td>ABC</td>
					<td>1</td>
					<td>Dhaka</td>
					<td>12345</td>
				</tr>
				<tr>
					<td>ABC</td>
					<td>1</td>
					<td>Dhaka</td>
					<td>12345</td>
				</tr>
				<tr>
					<td>ABC</td>
					<td>1</td>
					<td>Dhaka</td>
					<td>12345</td>
				</tr>
				<tr>
					<td>ABC</td>
					<td>1</td>
					<td>Dhaka</td>
					<td>12345</td>
				</tr>
				<tr>
					<td>ABC</td>
					<td>1</td>
					<td>Dhaka</td>
					<td>12345</td>
				</tr>
				<tr>
					<td>ABC</td>
					<td>1</td>
					<td>Dhaka</td>
					<td>12345</td>
				</tr>
				<tr>
					<td>ABC</td>
					<td>1</td>
					<td>Dhaka</td>
					<td>12345</td>
				</tr>
				<tr>
					<td>ABC</td>
					<td>1</td>
					<td>Dhaka</td>
					<td>12345</td>
				</tr>
				<tr>
					<td>ABC</td>
					<td>1</td>
					<td>Dhaka</td>
					<td>12345</td>
				</tr>
				<tr>
					<td>ABC</td>
					<td>1</td>
					<td>Dhaka</td>
					<td>12345</td>
				</tr>
				<tr>
					<td>ABC</td>
					<td>1</td>
					<td>Dhaka</td>
					<td>12345</td>
				</tr>
				<tr>
					<td>ABC</td>
					<td>1</td>
					<td>Dhaka</td>
					<td>12345</td>
				</tr>
				<tr>
					<td>ABC</td>
					<td>1</td>
					<td>Dhaka</td>
					<td>12345</td>
				</tr>
				<tr>
					<td>ABC</td>
					<td>1</td>
					<td>Dhaka</td>
					<td>12345</td>
				</tr>
				<tr>
					<td>ABC</td>
					<td>1</td>
					<td>Dhaka</td>
					<td>12345</td>
				</tr>
				
				</tbody>
				</table>
			</table>
		</div>
	</div>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
	<script type="text/javascript" src="//cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>

	<script type="text/javascript">
		$(document).ready( function () {
    		$('#myTable').DataTable();
		} );
	</script>
</body>
</html>